version: "3.9"

services:
  wazuh:
    image: wazuh/wazuh:4.6.0
    restart: always
    ports:
      - "1514:1514"
      - "1515:1515"
    volumes:
      - wazuh_data:/var/ossec/data
    environment:
      - TZ=UTC
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:1514"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  wazuh_data:
